language: r

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'



language: r

sudo: required

env: _R_CHECK_CRAN_INCOMING_=FALSE

r_packages:
  - covr
  - devtools

r_github_packages:

  - codecov/redguard
after_success:
  - Rscript -e 'library(covr);codecov()s